#!/bin/bash
# init
# =============================================
# SCRIPT COMMANDS
echo
echo "===============  START HFT Axodus Finance v0.1 ==============="
echo "- White Rabit Scalper Strategy                                "
echo "- Starting instance ...                                       "
echo "- Loading configuration files ...                             "
# =============================================
# EXECUTE SCRIPT
bin/hummingbot.py
